server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dkswoah589318!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        ddl-auto: create
        format_sql: true

logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace

